using System.ComponentModel;

namespace PolygonApiClient
{
    public enum QuoteConditions
    {
        [Description("Regular")] _0 = 0,
        [Description("RegularTwoSidedOpen")] _1 = 1,
        [Description("RegularOneSidedOpen")] _2 = 2,
        [Description("SlowAsk")] _3 = 3,
        [Description("SlowBid")] _4 = 4,
        [Description("SlowBidAsk")] _5 = 5,
        [Description("SlowDueLRPBid")] _6 = 6,
        [Description("SlowDueLRPAsk")] _7 = 7,
        [Description("SlowDueNYSELRP")] _8 = 8,
        [Description("SlowDueSetSlowListBidAsk")] _9 = 9,
        [Description("ManualAskAutomatedBid")] _10 = 10,
        [Description("ManualBidAutomatedAsk")] _11 = 11,
        [Description("ManualBidAndAsk")] _12 = 12,
        [Description("Opening")] _13 = 13,
        [Description("Closing")] _14 = 14,
        [Description("Closed")] _15 = 15,
        [Description("Resume")] _16 = 16,
        [Description("FastTrading")] _17 = 17,
        [Description("TradingRangeIndication")] _18 = 18,
        [Description("MarketMakerQuotesClosed")] _19 = 19,
        [Description("NonFirm")] _20 = 20,
        [Description("NewsDissemination")] _21 = 21,
        [Description("OrderInflux")] _22 = 22,
        [Description("OrderImbalance")] _23 = 23,
        [Description("DueToRelatedSecurityNewsDissemination")] _24 = 24,
        [Description("DueToRelatedSecurityNewsPending")] _25 = 25,
        [Description("AdditionalInformation")] _26 = 26,
        [Description("NewsPending")] _27 = 27,
        [Description("AdditionalInformationDueToRelatedSecurity")] _28 = 28,
        [Description("DueToRelatedSecurity")] _29 = 29,
        [Description("InViewOfCommon")] _30 = 30,
        [Description("EquipmentChangeover")] _31 = 31,
        [Description("NoOpenNoResponse")] _32 = 32,
        [Description("SubPennyTrading")] _33 = 33,
        [Description("AutomatedBidNoOfferNoBid")] _34 = 34,
        [Description("LULDPriceBand")] _35 = 35,
        [Description("MarketWideCircuitBreakerLevel1")] _36 = 36,
        [Description("MarketWideCircuitBreakerLevel2")] _37 = 37,
        [Description("MarketWideCircuitBreakerLevel3")] _38 = 38,
        [Description("RepublishedLULDPriceBand")] _39 = 39,
        [Description("OnDemandAuction")] _40 = 40,
        [Description("CashOnlySettlement")] _41 = 41,
        [Description("NextDaySettlement")] _42 = 42,
        [Description("LULDTradingPause")] _43 = 43,
        [Description("SLowDuelRPBidAsk")] _71 = 71,
        [Description("Cancel")] _80 = 80,
        [Description("Corrected_Price")] _81 = 81,
        [Description("SIPGenerated")] _82 = 82,
        [Description("Unknown")] _83 = 83,
        [Description("Crossed_Market")] _84 = 84,
        [Description("Locked_Market")] _85 = 85,
        [Description("Depth_On_Offer_Side")] _86 = 86,
        [Description("Depth_On_Bid_Side")] _87 = 87,
        [Description("Depth_On_Bid_And_Offer")] _88 = 88,
        [Description("Pre_Opening_Indication")] _89 = 89,
        [Description("Syndicate_Bid")] _90 = 90,
        [Description("Pre_Syndicate_Bid")] _91 = 91,
        [Description("Penalty_Bid")] _92 = 92,
        [Description("CQS_Generated")] _94 = 94
    }
}
