using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PolygonApiClient
{
    public enum TradeConditions
    {

        [Description("Regular Sale")] _0 = 0,
        [Description("Acquisition")] _1 = 1,
        [Description("Average Price Trade")] _2 = 2,
        [Description("Automatic Execution")] _3 = 3,
        [Description("Bunched Trade")] _4 = 4,
        [Description("Bunched Sold Trade")] _5 = 5,
        [Description("CAP Election")] _6 = 6,
        [Description("Cash Sale")] _7 = 7,
        [Description("Closing Prints")] _8 = 8,
        [Description("Cross Trade")] _9 = 9,
        [Description("Derivatively Priced")] _10 = 10,
        [Description("Distribution")] _11 = 11,
        [Description("Form T")] _12 = 12,
        [Description("Extended Trading Hours (Sold Out of Sequence)")] _13 = 13,
        [Description("Intermarket Sweep")] _14 = 14,
        [Description("Market Center Official Close")] _15 = 15,
        [Description("Market Center Official Open")] _16 = 16,
        [Description("Market Center Opening Trade")] _17 = 17,
        [Description("Market Center Reopening Trade")] _18 = 18,
        [Description("Market Center Closing Trade")] _19 = 19,
        [Description("Next Day")] _20 = 20,
        [Description("Price Variation Trade")] _21 = 21,
        [Description("Prior Reference Price")] _22 = 22,
        [Description("Rule 155 Trade (AMEX)")] _23 = 23,
        [Description("Rule 127 NYSE")] _24 = 24,
        [Description("Opening Prints")] _25 = 25,
        [Description("Opened")] _26 = 26,
        [Description("Stopped Stock (Regular Trade)")] _27 = 27,
        [Description("Re-Opening Prints")] _28 = 28,
        [Description("Seller")] _29 = 29,
        [Description("Sold Last")] _30 = 30,
        [Description("Sold Out")] _32 = 32,
        [Description("Sold (out of Sequence)")] _33 = 33,
        [Description("Split Trade")] _34 = 34,
        [Description("Stock Option")] _35 = 35,
        [Description("Yellow Flag Regular Trade")] _36 = 36,
        [Description("Odd Lot Trade")] _37 = 37,
        [Description("Corrected Consolidated Close (per listing market)")] _38 = 38,
        [Description("Unknown")] _39 = 39,
        [Description("Held")] _40 = 40,
        [Description("Trade Thru Exempt")] _41 = 41,
        [Description("NonEligible")] _42 = 42,
        [Description("NonEligible Extended")] _43 = 43,
        [Description("Cancelled")] _44 = 44,
        [Description("Recovery")] _45 = 45,
        [Description("Correction")] _46 = 46,
        [Description("As of")] _47 = 47,
        [Description("As of Correction")] _48 = 48,
        [Description("As of Cancel")] _49 = 49,
        [Description("OOB")] _50 = 50,
        [Description("Summary")] _51 = 51,
        [Description("Contingent Trade")] _52 = 52,
        [Description("Qualified Contingent Trade (QCT)")] _53 = 53,
        [Description("Errored")] _54 = 54,
        [Description("OPENING_REOPENING_TRADE_DETAIL")] _55 = 55,
        [Description("Placeholder")] _56 = 56,
        [Description("Short Sale Restriction Activated,")] _57 = 57,
        [Description("Short Sale Restriction Continued")] _58 = 58,
        [Description("Short Sale Restriction Deactivated")] _59 = 59,
        [Description("Short Sale Restriction In Effect")] _60 = 60,
        [Description("Financial Status - Bankrupt")] _62 = 62,
        [Description("Financial Status - Deficient")] _63 = 63,
        [Description("Financial Status - Delinquent")] _64 = 64,
        [Description("Financial Status - Bankrupt and Deficient")] _65 = 65,
        [Description("Financial Status - Bankrupt and Delinquent")] _66 = 66,
        [Description("Financial Status - Deficient and Delinquent")] _67 = 67,
        [Description("Financial Status - Deficient Delinquent and Bankrupt")] _68 = 68,
        [Description("Financial Status - Liquidation")] _69 = 69,
        [Description("Financial Status - Creations Suspended")] _70 = 70,
        [Description("Financial Status - Redemptions Suspended")] _71 = 71,
        [Description("Canceled")] _201 = 201,
        [Description("Late and Out Of Sequence")] _202 = 202,
        [Description("Last and Canceled")] _203 = 203,
        [Description("Late")] _204 = 204,
        [Description("Opening Trade and Canceled")] _205 = 205,
        [Description("Opening Trade Late Out of Sequence")] _206 = 206,
        [Description("Only Trade and Canceled")] _207 = 207,
        [Description("Opening Trade and Late")] _208 = 208,
        [Description("Automatic Execution")] _209 = 209,
        [Description("Reopening Trade")] _210 = 210,
        [Description("Intermarket Sweep Order")] _219 = 219,
        [Description("Single Leg Auction Non ISO")] _227 = 227,
        [Description("Single Leg Auction ISO")] _228 = 228,
        [Description("Single Leg Cross Non ISO")] _229 = 229,
        [Description("Single Leg Cross ISO")] _230 = 230,
        [Description("Single Leg Floor Trade")] _231 = 231,
        [Description("Multi Leg auto-electronic trade")] _232 = 232,
        [Description("Multi Leg Auction")] _233 = 233,
        [Description("Multi Leg Cross")] _234 = 234,
        [Description("Multi Leg floor trade")] _235 = 235,
        [Description("Multi Leg auto-electronic trade against single leg(s)")] _236 = 236,
        [Description("Stock Options Auction")] _237 = 237,
        [Description("Multi Leg Auction against single leg(s)")] _238 = 238,
        [Description("Multi Leg floor trade against single leg(s)")] _239 = 239,
        [Description("Stock Options auto-electronic trade")] _240 = 240,
        [Description("Stock Options Cross")] _241 = 241,
        [Description("Stock Options floor trade")] _242 = 242,
        [Description("Stock Options auto-electronic trade against single leg(s)")] _243 = 243,
        [Description("Stock Options Auction against single leg(s)")] _244 = 244,
        [Description("Stock Options floor trade against single leg(s)")] _245 = 245,
        [Description("Multi Leg Floor Trade of Proprietary Products")] _246 = 246,
        [Description("Multilateral Compression Trade of Proprietary Products")] _247 = 247,
        [Description("Extended Hours Trade")] _248 = 248,
    }
}
